XIVO_LIB_PYTHON_PYTHONPATH=$(XIVO_PATH)/xivo-lib-python/xivo-lib-python
XIVO_DAO_PYTHONPATH=$(XIVO_PATH)/xivo-dao/xivo-dao
XIVO_DIRD_PYTHONPATH=$(XIVO_PATH)/xivo-dird/xivo-dird
XIVO_AGENT_PYTHONPATH=$(XIVO_PATH)/xivo-agent/xivo-agent
XIVO_PROVD_PYTHONPATH=$(XIVO_PATH)/xivo-provisioning/xivo-provisioning/src
XIVO_CTID_PYTHONPATH=$(XIVO_PATH)/xivo-ctid/xivo-ctid

XIVO_PYTHONPATH=$(XIVO_LIB_PYTHON_PYTHONPATH):$(XIVO_DAO_PYTHONPATH):$(XIVO_DIRD_PYTHONPATH):$(XIVO_AGENT_PYTHONPATH):$(XIVO_PROVD_PYTHONPATH):$(XIVO_CTID_PYTHONPATH)

cti.unittest:
	PYTHONPATH=PYTHONPATH:$(XIVO_PYTHONPATH) nosetests $(XIVO_CTID_PYTHONPATH)/xivo_cti
